export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as Login} from './Login'
export {default as Reg} from './Reg'
export {default as Finished} from './Finished'